import './css/main.scss';
import './fonts/IBMPlexSans-Bold.ttf';
import './fonts/IBMPlexSans-Light.ttf';
import './js/intersection-observer-polyfill';
import './js/app';
import './js/carousel';
import './js/event-handler';
import './js/side-nav';
import './js/animate-on-scroll';