import './css/main.scss';
import './fonts/IBMPlexSans-Bold.ttf';
import './fonts/IBMPlexSans-Light.ttf';
import './js/app';
import './js/countdown';
import './js/side-nav';
import './js/registration';
import './js/map'
import './images/favicon.ico'